export CVSEDITOR=nvim
export EDITOR=nvim
export VISUAL=nvim
export GOPATH=~/opt/go

typeset -U fpath
fpath=(~/.zsh/functions $fpath)
export FPATH

typeset -U path
path=(~/bin $GOPATH/bin $path)
export PATH
