alias ls='ls --color=auto'

autoload -Uz add-zsh-hook
autoload -Uz colors; colors
autoload -Uz compinit; compinit
autoload -Uz vi-mode-init; vi-mode-init
autoload -Uz vcs_info

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

KEYTIMEOUT=20

eval "$(dircolors ~/.zsh/misc/dircolors.256dark)"

PROMPT='%F{default}%m%f %F{blue}%10<…<%~%<<%f %F{blue}%1v%f-%F{white}%#%f '
RPROMPT='%F{red}%(?..[%?] )%f$vcs_info_msg_0_'

zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' get-revision true
zstyle ':vcs_info:*' actionformats '(%F{cyan}%s%F{blue}:%F{green}%b@%.5i%F{blue}|%F{red}%a%f)'
zstyle ':vcs_info:*' formats '(%F{cyan}%s%F{blue}:%F{green}%b@%F{default}%.5i%f)'
add-zsh-hook precmd vcs_info

setopt APPEND_HISTORY		# append their history list to the history file, rather than  replace it
setopt EXTENDED_HISTORY		# save timestamp and duration to the history
setopt HIST_IGNORE_ALL_DUPS	# remove copies of lines still in the history list
setopt HIST_IGNORE_SPACE	# lines which begin with a space don't go into the history
setopt HIST_REDUCE_BLANKS	# remove superfluous blanks from each command line
setopt HIST_SAVE_NO_DUPS	# older commands that duplicate newer ones are omitted on history writing
setopt HIST_VERIFY		# perform history expansion and reload the line into the editing buffer
setopt INC_APPEND_HISTORY	# each line is added to the history in this way as it is executed
setopt NO_BEEP			# no beep on error in ZLE
setopt NUMERIC_GLOB_SORT	# sort the filenames numerically
setopt PROMPT_SUBST		# expansions are performed in prompts
setopt RM_STAR_SILENT		# do not query the user before executing `rm *' or `rm path/*'
setopt SHARE_HISTORY		# re-share history after every command

bindkey -M vicmd '/'	history-incremental-search-backward
bindkey -M vicmd '?'	history-incremental-search-forward
bindkey -M viins '^i'	expand-or-complete-prefix

# <Up>
bindkey -M vicmd "^[[A"	history-beginning-search-backward
bindkey -M viins "^[[A"	history-beginning-search-backward
# <Down>
bindkey -M vicmd "^[[B"	history-beginning-search-forward
bindkey -M viins "^[[B"	history-beginning-search-forward
# <Insert>
bindkey -M vicmd "^[[2~"	vi-insert
bindkey -M viins "^[[2~"	vi-insert
# <Del>
bindkey -M vicmd "^[[3~"	vi-delete-char
bindkey -M viins "^[[3~"	vi-delete-char
# <Home>
bindkey -M vicmd "^[[1~"	vi-beginning-of-line
bindkey -M vicmd "^[[7~"	vi-beginning-of-line
bindkey -M vicmd "^[[H"		vi-beginning-of-line
bindkey -M viins "^[[1~"	vi-beginning-of-line
bindkey -M viins "^[[7~"	vi-beginning-of-line
bindkey -M viins "^[[H"		vi-beginning-of-line
# <End>
bindkey -M vicmd "^[[4~"	vi-end-of-line
bindkey -M vicmd "^[[8~"	vi-end-of-line
bindkey -M vicmd "^[[F"		vi-end-of-line
bindkey -M viins "^[[4~"	vi-end-of-line
bindkey -M viins "^[[8~"	vi-end-of-line
bindkey -M viins "^[[F"		vi-end-of-line
# <PageUp>
bindkey -M vicmd "^[[5~"	vi-backward-word
bindkey -M viins "^[[5~"	vi-backward-word
# <PageDown>
bindkey -M vicmd "^[[6~"	vi-forward-word
bindkey -M viins "^[[6~"	vi-forward-word

bindkey -M viins "^W"		vi-backward-kill-word

